### ISSUE TITLE
Error saving image: The image format could not be determined

### ISSUE THREAD

**Issue by neomikr0n** [Kirottu/watershot#12]
Hey! Perhaps I'm doing something wrong, can't get it to work, thanks in advance!

`watershot -c path ~/Pictures/`
```
[2023-05-23T22:09:07Z ERROR watershot] Error saving image: The image format could not be determined
```
---
`watershot --stdout | swappy`
```
** (swappy:1594341): CRITICAL **: 15:34:45.950: original image not loaded
[2023-05-23T21:34:47Z ERROR watershot] Failed to write image content to stdout: Broken pipe (os error 32)
```
---
`watershot --stdout | ksnip`
```
Critical: Unknown wayland platform, using default wayland Image Grabber.
[2023-05-23T22:03:36Z ERROR watershot] Failed to write image content to stdout: Broken pipe (os error 32)
```

neofetch:
```
OS: Garuda Linux 
Kernel: 6.3.1-zen2-1-zen 
Uptime: 5 hours, 11 mins 
Packages: 2084 (pacman) 
Shell: bash 
DE: Hyprland 
WM: sway 
Terminal: foot 
CPU: 13th Gen Intel i5-13600K (20) @ 5.2GHz 
GPU: AMD ATI Radeon RX 6650 XT / 6700S / 6800S 
Memory: 11.19GiB / 31.12GiB 
```

**Comment by Kirottu** [comment]
The saving part is due to you not providing a valid filename, use `watershot -c directory ~/Pictures/` to make it automatically generate a filename.

The broken pipe issue appears for me too and I am not quite sure what causes it.

**Comment by neomikr0n** [comment]
I'm not sure if I understand you correctly, but the command you suggest gives me the exact same error, enter rectangle mode tho:
**`watershot -c directory ~/Pictures/`**

```
[2023-05-24T06:23:42Z ERROR watershot] Error saving image: The image format could not be determined
```

So, no automatically generate a filename for me.

Also, if I want the filename to have a format like these `ss_$Y-$M-$D_$h-$m_$s_garuda.png` what command should I enter, thanks in advance!

**Comment by Kirottu** [comment]
Yeah I found out that the file extension for the auto generated filename was missing, as for the pipe problem it's weird. If I pipe into something like `feh -` it works fine but swappy isn't too happy about it.
