### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by mochaaP** [Kirottu/watershot#13]
Watershot currently doesn't respect output scale factor.

**Comment by Kirottu** [comment]
Hi, sorry for the silence.

My most recent commits should enable basic HiDPI support, so testing of them would be much appreciated.

**Comment by Kirottu** [comment]
Yep that I am aware of, but am not sure on how to solve it.

**Comment by Kirottu** [comment]
Alright I think I figured it out the best I can, give it a try now.

**Comment by mochaaP** [comment]
The selection outline (`line_width`) is not showing after <https://github.com/Kirottu/watershot/commit/47005dd8a44ee2c9d526aab3e692502548823328>

**Comment by Kirottu** [comment]
Alright that should also be fixed now.
