### ISSUE TITLE
Support WebP Format

### ISSUE THREAD

**Issue by Volkor3-16** [Kirottu/watershot#2]
I haven't looked at the code (yet.. hopefully), but with my testing it seems webp isn't supported, while it is /somewhat/ supported in the image crate with the libwebp library.

Would it be possible to add support for it?

**Comment by Kirottu** [comment]
Sorry for the late reply! Somehow this issue completely slipped through the cracks and I was never aware of it.

It is probably possible to support the WEBP format, but don't have any concrete information on it right now. What would be the reason for adding support for it anyway?

**Comment by Volkor3-16** [comment]
Mostly the file size improvements, my server deletes uploaded files depending on their filesize, so smaller files last longer.

**Comment by Kirottu** [comment]
Alright that's fair, I'll look into it when I have time.

**Comment by Kirottu** [comment]
Alright, with the latest commit it should be able to save images with the WEBP format.
