### ISSUE TITLE
Missing editing tools around `grim`-like selector

### ISSUE THREAD

**Issue by ndom91** [Kirottu/watershot#3]
So maybe my expectations are wrong, but I was expecting some editing tools to be visible around the selection, like with `flameshot`.

However, when I start `watershot` I just get the "RECTANGLE MODE"/"DISPLAY MODE" label and `grim`-like rectangle selector. Once I've selected an area (in rectangle mode, for example), nothing else happens. I can only exit out of the selection with `Enter` or `Esc`. 

Like I said above, I expected some editing tools (like insert text, draw boxes, arrows, etc.) to appear around the selection like `flameshot` does, or at the very least that the selection to get piped into `swappy` or another simple editing tool. Is this something watershot expects the user to do? i.e. `watershot | swappy -f` ?

The fact that the `watershot` config supports different tool config options confuses me then though.. I'm almost positive it's supposed to function like `flameshot` :joy:

**Comment by Kirottu** [comment]
Such tools, at least right now are not a thing. It is flameshot-like in the experience of having a static full screen screenshot that you can pick a region from but does not offer any other editing.

Such editing tools would be possible to implement, but would be quite time consuming and difficult to get right.

**Comment by Kirottu** [comment]
Yes, they are just for the appearance.

Stdout for the selected image should be implemented and I will work on it when I have time.

**Comment by Kirottu** [comment]
Alright, it was quite simple to do that and the latest commit supports outputting the screenshot to stdout in PNG format using the `--stdout` flag.
