### ISSUE TITLE
Doesn't work with latest Hyprland version

### ISSUE THREAD

**Issue by akshettrj** [Kirottu/watershot#30]
I am running the following versions:

* ```Hyprland, built from branch main at commit 56adec7c1a49c079f320ba3c0c5ae3948946a9e5 dirty (socket2: emit lockgroups event (3317)). Tag: v0.29.1-78-g56adec7c```
* ```watershot 0.2.1``` (Compiled from source)

It seems that watershot is using an older version of hyprland library which supports only i16 window IDs

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `18446744073709551615`, expected i16", line: 12, column: 35))', src/window/hyprland.rs:25:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kirottu** [comment]
Alright this should now be fixed on the master branch, can you try it out?

**Comment by Kirottu** [comment]
Yep fixed that issue now, and made a new release as well.
