### ISSUE TITLE
Support for "instant" mode

### ISSUE THREAD

**Issue by JustSimplyKyle** [Kirottu/watershot#4]
basically just like how grim works

**Comment by Kirottu** [comment]
Well, Watershot just uses grim on the backend to capture the screen right now anyway. So I'm not quite sure what the point of this would be.

**Comment by JustSimplyKyle** [comment]
It freezes the screen from my testing

**Comment by Kirottu** [comment]
It doesn't "freeze" the screen really, that's basically an illusion. It just shows a screenshot taken with grim on all of the displays with layer shell. And then it lets you select from that view.

**Comment by n3oney** [comment]
> It freezes the screen from my testing

you might be able to use this script:
```bash
#!/usr/bin/env bash
hyprpicker -r -z &
picker_proc=$!
grim
kill $picker_proc
```

(modify to your usecase)

**Comment by JustSimplyKyle** [comment]
https://github.com/hyprwm/hyprpicker/issues/30
I actually *do* use that script, but it currently suffers from this script

**Comment by n3oney** [comment]
> https://github.com/hyprwm/hyprpicker/issues/30
> 
> I actually *do* use that script, but it currently suffers from this script 

Ah, okay. I used to have a script that did take a screenshot too before, but it had a slight problem (it used a window for showing the screenshot, so it would move the windows a bit)
